version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=macbookpro
      - POSTGRES_PASSWORD=1111   
      - POSTGRES_DB=casbin
    networks:
      - google
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  api-services:
    container_name: api_gateway
    build: .
    depends_on:
      db:
        condition: service_started
    networks:
      - google
    ports:
      - "9876:9876"

networks:
  google:
    name: google
    driver: bridge
    external: true

volumes:
  db-data: