version: '3.9'

services:
 postgres-db3:
   container_name: postgres3
   image: postgres
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=casbin
   ports:
     - "5435:5432"
   volumes:
     - db:/data/postgres3
   networks:
     - google

  api-services:
    container_name: api_gateway
    build: .
    depends_on:
      db:
        condition: service_started
    networks:
      - google
    ports:
      - "9876:9876"

networks:
  google:
    name: google
    driver: bridge
    external: true

volumes:
  db: